Type fixes
BillSchumacher/Auto-GPT pull request #6
Opened 2023-04-17 19:44 UTC by TaylorBeeston

I just copied over the plugin template ABC and then better typed each hook. Doing that, I found a couple small bugs and fixed those as well!

2023-04-17 21:54 UTC, BillSchumacher requested changes

2023-04-17 21:54 UTC, BillSchumacher commented on autogpt/plugin_template.py
You can import this class from pip.

2023-04-18 05:11 UTC, TaylorBeeston commented on autogpt/plugin_template.py
I didn't realize that guy was up already! Do you mind updating what's on pypi with the type changes that got merged in today?

2023-04-18 05:33 UTC, TaylorBeeston commented
@BillSchumacher one thing I forgot in this PR: the `post_planning` function has the wrong type right now. As it is used, it is getting parsed JSON and should be returning parsed JSON, but the ABC type is expecting a string and returning a string. I'm not sure whether strings or dicts should be preferred here, so I wanted to get your input before making that decision

2023-04-18 22:57 UTC, BillSchumacher approved these changes

2023-04-18 22:57 UTC, merged

2023-04-18 22:57 UTC, BillSchumacher commented
> @BillSchumacher one thing I forgot in this PR: the `post_planning` function has the wrong type right now. As it is used, it is getting parsed JSON and should be returning parsed JSON, but the ABC type is expecting a string and returning a string. I'm not sure whether strings or dicts should be preferred here, so I wanted to get your input before making that decision

No problem, thanks for the PR!